package DrMuhamadMubarak.TheFuture.generator.ai;

public class ThePrompt {
    public static final String PROMPT_TEMPLATE = """
             Generate a JSON structure for a Spring Boot project that defines entities and their attributes, including relationships such as @OneToMany, @ManyToOne, @OneToOne, and @ManyToMany. The JSON should follow these rules:
            \s
                 Each entity must have a unique name and a list of attributes.
                 Attributes must include attributeName, dataType, and optional fields like isPrimaryKey, isAutoGenerated, dataSize, and defaultValue.
                 For relationship attributes, include relationshipType (e.g., ONE_TO_MANY, MANY_TO_ONE, ONE_TO_ONE, MANY_TO_MANY), relatedEntity (the target entity), and mappedBy (for inverse relationships).
                 Ensure all relationship attributes are marked as isNullable: true to avoid @Column(nullable = false) annotations.
                 For @ManyToOne and @OneToOne relationships, use @JoinColumn instead of @Column.
                 For @ManyToMany relationships, specify the owning side (without mappedBy) and the inverse side (with mappedBy).
                 All classes and attribute names must be a single word(This is very important).
            \s
             Additionally, the JSON must always include two predefined entities:
            \s
             {
               "name": "User",
               "attributes": [
                 {
                   "attributeName": "id",
                   "dataType": "Long",
                   "isPrimaryKey": true,
                   "isAutoGenerated": true
                 },
                 {
                   "attributeName": "username",
                   "dataType": "String"
                 },
                 {
                   "attributeName": "password",
                   "dataType": "String"
                 },
                 {
                   "attributeName": "roles",
                   "dataType": "Set<Role>",
                   "relationshipType": "MANY_TO_MANY",
                   "relatedEntity": "Role",
                   "isNullable": true
                 }
               ]
             }
            \s
             {
               "name": "Role",
               "attributes": [
                 {
                   "attributeName": "id",
                   "dataType": "Long",
                   "isPrimaryKey": true,
                   "isAutoGenerated": true
                 },
                 {
                   "attributeName": "name",
                   "dataType": "String"
                 }
               ]
             }
            \s
             Example JSON structure:
            \s
             {
               "entities": [
                 {
                   "name": "Author",
                   "attributes": [
                     {
                       "attributeName": "id",
                       "dataType": "Long",
                       "isPrimaryKey": true,
                       "isAutoGenerated": true
                     },
                     {
                       "attributeName": "name",
                       "dataType": "String",
                       "dataSize": "100"
                     },
                     {
                       "attributeName": "books",
                       "dataType": "List<Book>",
                       "relationshipType": "ONE_TO_MANY",
                       "relatedEntity": "Book",
                       "mappedBy": "author",
                       "isNullable": true
                     }
                   ]
                 },
                 {
                   "name": "Book",
                   "attributes": [
                     {
                       "attributeName": "id",
                       "dataType": "Long",
                       "isPrimaryKey": true,
                       "isAutoGenerated": true
                     },
                     {
                       "attributeName": "title",
                       "dataType": "String",
                       "dataSize": "255"
                     },
                     {
                       "attributeName": "author",
                       "dataType": "Author",
                       "relationshipType": "MANY_TO_ONE",
                       "relatedEntity": "Author",
                       "isNullable": true
                     }
                   ]
                 },
                 {
                   "name": "Student",
                   "attributes": [
                     {
                       "attributeName": "id",
                       "dataType": "Long",
                       "isPrimaryKey": true,
                       "isAutoGenerated": true
                     },
                     {
                       "attributeName": "name",
                       "dataType": "String"
                     },
                     {
                       "attributeName": "courses",
                       "dataType": "List<Course>",
                       "relationshipType": "MANY_TO_MANY",
                       "relatedEntity": "Course",
                       "isNullable": true
                     }
                   ]
                 },
                 {
                   "name": "Course",
                   "attributes": [
                     {
                       "attributeName": "id",
                       "dataType": "Long",
                       "isPrimaryKey": true,
                       "isAutoGenerated": true
                     },
                     {
                       "attributeName": "title",
                       "dataType": "String"
                     },
                     {
                       "attributeName": "students",
                       "dataType": "List<Student>",
                       "relationshipType": "MANY_TO_MANY",
                       "relatedEntity": "Student",
                       "mappedBy": "courses",
                       "isNullable": true
                     }
                   ]
                 }
               ]
             }
            \s
             Ensure that every generated JSON follows these rules and always includes the User and Role entities without modification while allowing additional entities to be dynamically defined according to\s
             the same principles.
            \s
             The project will be about: %s and the project should be realistic and not simple.
            \s
             IMPORTANT: Return only the JSON and nothing else. Do not include any explanations, comments, or additional text.
            \s""";
}
