package DrMuhamadMubarak.TheFuture.Generator.Builder;

import DrMuhamadMubarak.TheFuture.Generator.DTO.AttributeDTO;

public class AttributeBuilder {
    public static AttributeDTO createAttributeDTO(
            String attributeName, String dataTypeStr, String dataSize, String defaultValue,
            Boolean isPrimaryKey, Boolean isNullable, String relationshipTypeStr, Boolean isAutoGenerated, String relatedEntity, String mappedBy) {
        boolean primaryKey = isPrimaryKey != null ? isPrimaryKey : false;
        boolean nullable = isNullable != null ? isNullable : true;
        boolean autoGenerated = isAutoGenerated != null ? isAutoGenerated : false;

        return new AttributeDTO(
                attributeName,
                dataTypeStr,
                dataSize,
                defaultValue,
                autoGenerated,
                primaryKey,
                nullable,
                relationshipTypeStr,
                relatedEntity,
                mappedBy
        );
    }
}
