package DrMuhamadMubarak.TheFuture.generator.builder;

import DrMuhamadMubarak.TheFuture.generator.dto.AttributeDTO;

public class AttributeBuilder {
    public static AttributeDTO createAttributeDTO(
            String attributeName, String dataTypeStr, String dataSize, String defaultValue,
            Boolean isPrimaryKey, Boolean isNullable, String relationshipTypeStr, Boolean isAutoGenerated, String relatedEntity, String mappedBy) {
        boolean primaryKey = isPrimaryKey != null ? isPrimaryKey : false;
        boolean nullable = isNullable != null ? isNullable : true;
        boolean autoGenerated = isAutoGenerated != null ? isAutoGenerated : false;

        return AttributeDTO.builder()
                .attributeName(attributeName)
                .dataType(dataTypeStr)
                .dataSize(dataSize)
                .defaultValue(defaultValue)
                .isAutoGenerated(autoGenerated)
                .isPrimaryKey(primaryKey)
                .isNullable(nullable)
                .relationshipType(relationshipTypeStr)
                .relatedEntity(relatedEntity)
                .mappedBy(mappedBy)
                .build();
    }
}
