package DrMuhamadMubarak.TheFuture.Generator.DTO;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class AttributeDTO {

    @NotBlank(message = "Attribute Name is required")
    @JsonProperty("attributeName")
    private String attributeName;

    @NotBlank(message = "Data Type is required")
    @JsonProperty("dataType")
    private String dataType;

    @JsonProperty("dataSize")
    private String dataSize;

    @JsonProperty("defaultValue")
    private String defaultValue;

    @JsonProperty("isAutoGenerated")
    private boolean isAutoGenerated;

    @JsonProperty("isPrimaryKey")
    private boolean isPrimaryKey;

    @JsonProperty("isNullable")
    private boolean isNullable;

    @JsonProperty("relationshipType")
    private String relationshipType;

    @JsonProperty("relatedEntity")
    private String relatedEntity;

    @JsonProperty("mappedBy")
    private String mappedBy;
}