package DrMuhamadMubarak.TheFuture.Generator.DTO;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Data
public class AttributeDTO {

    private String attributeName;
    private String dataType;
    private String dataSize;
    private String defaultValue;
    private boolean isAutoGenerated;
    private boolean isPrimaryKey;
    private boolean isNullable;
    private String relationshipType;
}
