package DrMuhamadMubarak.TheFuture.Generator.DTO;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Data
public class AttributeDTO {

    @NotBlank(message = "Attribute Name is required")
    private String attributeName;

    @NotBlank(message = "Data Type is required")
    private String dataType;

    private String dataSize;
    private String defaultValue;
    private boolean isAutoGenerated;
    private boolean isPrimaryKey;
    private boolean isNullable;
    private String relationshipType;
}
