package DrMuhamadMubarak.TheFuture.Generator.Controller;

import DrMuhamadMubarak.TheFuture.Generator.DTO.AttributeDTO;
import DrMuhamadMubarak.TheFuture.Generator.Service.ProjectAttributeService;
import DrMuhamadMubarak.TheFuture.Generator.Service.ProjectEntitiesService;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

import java.io.IOException;

@Controller
@AllArgsConstructor
public class ProjectAttributeController {

    private final ProjectEntitiesService projectEntitiesService;
    private final ProjectAttributeService projectAttributeService;

    @GetMapping("/add-attributes")
    public String showAddAttributesPage(@RequestParam("projectName") String projectName,
                                        @RequestParam("entityName") String entityName,
                                        Model model) {
        model.addAttribute("projectName", projectName);
        model.addAttribute("entityName", entityName);
        return "add-attributes";
    }

    @PostMapping("/save-attributes")
    public String saveAttributes(
            @RequestParam("projectName") String projectName,
            @RequestParam("entityName") String entityName,
            @RequestParam("action") String action,
            @RequestParam(value = "attributeName") String attributeName,
            @RequestParam(value = "dataType") String dataTypeStr,
            @RequestParam(value = "dataSize", required = false) String dataSize,
            @RequestParam(value = "defaultValue", required = false) String defaultValue,
            @RequestParam(value = "isPrimaryKey", required = false) Boolean isPrimaryKey,
            @RequestParam(value = "isNullable", required = false) Boolean isNullable,
            @RequestParam(value = "relationshipType", required = false) String relationshipTypeStr,
            @RequestParam(value = "isAutoGenerated", required = false) Boolean isAutoGenerated,
            @RequestParam(value = "relatedEntity", required = false) String relatedEntity,
            @RequestParam(value = "mappedBy", required = false) String mappedBy,
            Model model) {

        try {
            AttributeDTO attribute = createAttributeDTO(
                    attributeName, dataTypeStr, dataSize, defaultValue,
                    isPrimaryKey, isNullable, relationshipTypeStr, isAutoGenerated, relatedEntity, mappedBy
            );

            projectAttributeService.addAttributesToEntity(projectName, entityName, attribute);
            model.addAttribute("projectName", projectName);

            if ("next".equals(action)) {
                return handleNextAction(projectName, entityName, model);
            } else {
                model.addAttribute("entityName", entityName);
                return "add-attributes";
            }
        } catch (IOException e) {
            model.addAttribute("message", "An error occurred: " + e.getMessage());
            return "error";
        }
    }

    private AttributeDTO createAttributeDTO(
            String attributeName, String dataTypeStr, String dataSize, String defaultValue,
            Boolean isPrimaryKey, Boolean isNullable, String relationshipTypeStr, Boolean isAutoGenerated, String relatedEntity, String mappedBy) {
        boolean primaryKey = isPrimaryKey != null ? isPrimaryKey : false;
        boolean nullable = isNullable != null ? isNullable : true;
        boolean autoGenerated = isAutoGenerated != null ? isAutoGenerated : false;

        return new AttributeDTO(
                attributeName,
                dataTypeStr,
                dataSize,
                defaultValue,
                autoGenerated,
                primaryKey,
                nullable,
                relationshipTypeStr,
                relatedEntity,
                mappedBy
        );
    }

    private String handleNextAction(String projectName, String entityName, Model model) throws IOException {
        projectEntitiesService.generateServiceClass(projectName, entityName, projectAttributeService.getAttributes());
        projectEntitiesService.generateControllerClass(projectName, entityName);
        projectEntitiesService.generateUI(projectName, entityName, projectAttributeService.getAttributes());

        projectAttributeService.clearAttributes();

        if (projectEntitiesService.isLastEntity(entityName)) {
            model.addAttribute("message", "Project generated successfully");
            return "result";
        } else {
            model.addAttribute("entityName", projectEntitiesService.getNextEntityName(entityName));
            return "add-attributes";
        }
    }
}